python -u run.py \
--task_name anomaly_detection \
--is_training 1 \
--root_path dataset/ \
--model GPT4TS \
--seq_len 100 \
--d_model 1280 \
--d_ff 1280 \
--enc_in 38 \
--c_out 38 \
--local_bs 64 \
--mask_ratio 0.2 \
--gpu 1 \
--local_epoch 2 \
--dataset_names '[ "UCR", "SMD", "MSL","PSM", "SWAT"]' \
--dataset_device '{"UCR": 2, "SMD": 2, "MSL": 2, "PSM": 2, "SWAT": 2}' \
